trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: MavenAuthenticate@0
  inputs:
    serverEndpoint: 'YourServiceConnection'

- task: UseMavenVersion@0
  inputs:
    versionSpec: '3.x'
    checkLatest: true

- script: mvn -B clean install
  displayName: 'Maven Build and Install'

- script: mvn -B test
  displayName: 'Run Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    failTaskOnFailedTests: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/target'
    artifact: 'drop'
